title = "My Hugo New Site"

languageCode = "en-us"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir= true

theme = "learn"

# Search functionality
[outputs]
home = ["HTML","RSS","JSON"]
section = ["HTML","RSS","JSON"]
